<?php
require __DIR__.'/config.php'; require_login();
function ovpn_users(){ $rows=[]; try{ $res=db()->query('SELECT id,username,blocked,created_at,updated_at FROM ovpn_users ORDER BY id DESC'); while($res && $row=$res->fetchArray(SQLITE3_ASSOC)) $rows[]=$row; }catch(Throwable $e){} return $rows; }
function ovpn_logs($limit=80){ $rows=[]; try{ $st=db()->prepare("SELECT * FROM ovpn_events WHERE event_type='connect' ORDER BY id DESC LIMIT :l"); $st->bindValue(':l',(int)$limit,SQLITE3_INTEGER); $r=$st->execute(); while($r && $row=$r->fetchArray(SQLITE3_ASSOC)) $rows[]=$row; }catch(Throwable $e){} return $rows; }
function parse_status_file($file){ $rows=[]; if(!is_readable($file)) return $rows; foreach(file($file,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES) as $line){ $line=trim($line); if(strpos($line,'CLIENT_LIST')!==0) continue; $p=preg_split('/[,\t]/',$line); if(count($p)<3) continue; if(count($p)>=10){$rows[]=['common_name'=>$p[1]??'','real_address'=>$p[2]??'','virtual_address'=>$p[3]??'','bytes_received'=>(int)($p[5]??0),'bytes_sent'=>(int)($p[6]??0),'connected_since'=>$p[7]??'','username'=>$p[9]??($p[1]??''),'client_id'=>$p[10]??'','cipher'=>$p[count($p)-1]??''];} else {$rows[]=['common_name'=>$p[1]??'','real_address'=>$p[2]??'','virtual_address'=>'','bytes_received'=>(int)($p[3]??0),'bytes_sent'=>(int)($p[4]??0),'connected_since'=>$p[5]??'','username'=>$p[1]??'','client_id'=>'','cipher'=>$p[count($p)-1]??''];} } return $rows; }
function last_gui_for_user($u){ try{ $st=db()->prepare("SELECT gui_version FROM ovpn_events WHERE username=:u AND COALESCE(gui_version,'')<>'' ORDER BY id DESC LIMIT 1"); $st->bindValue(':u',$u,SQLITE3_TEXT); $r=$st->execute(); $row=$r?$r->fetchArray(SQLITE3_ASSOC):false; return $row['gui_version']??''; }catch(Throwable $e){ return ''; } }
function active_clients(){ $rows=[]; foreach(['/var/log/openvpn/openvpn-status-udp.log'=>'UDP','/var/log/openvpn/openvpn-status-tcp.log'=>'TCP'] as $file=>$src){ foreach(parse_status_file($file) as $r){ $r['source']=$src; if(($r['username']??'')==='') $r['username']=$r['common_name']??''; $r['gui_version']=last_gui_for_user($r['username']); $rows[]=$r; } } return $rows; }
function valid_username($u){ return preg_match('/^[A-Za-z0-9._-]{3,32}$/',$u); }
$msg='';$err=''; if($_SERVER['REQUEST_METHOD']==='POST'){ $a=$_POST['action']??''; $u=trim($_POST['username']??$_POST['edit_username']??''); $p=$_POST['password']??$_POST['edit_password']??''; if(in_array($a,['add','edit'],true)){ if(!valid_username($u)){$err='Invalid username. Use 3-32 chars: A-Z a-z 0-9 . _ -';} elseif($p===''){$err='Password required';} else { [$code,$out]=cli('sudo -n /usr/local/bin/ovpn-user-manage.sh '.($a==='edit'?'update':'add').' '.escapeshellarg($u).' '.escapeshellarg($p)); $code===0?$msg=$out:$err=$out; } } elseif(in_array($a,['delete','block','unblock'],true)){ if(!valid_username($u)){$err='Invalid username';} else { [$code,$out]=cli('sudo -n /usr/local/bin/ovpn-user-manage.sh '.$a.' '.escapeshellarg($u)); $code===0?$msg=$out:$err=$out; } } }
$users=ovpn_users(); $active=active_clients(); $logs=ovpn_logs(); $activeBy=[]; foreach($active as $a){$u=$a['username']?:$a['common_name']; $activeBy[$u]=($activeBy[$u]??0)+1;} render_header('OpenVPN Panel'); ?>
<div class="panel-banner"><div class="toolbar"><div><h2 class="section-title">OpenVPN Live Panel</h2><div class="small"><span class="live-dot"></span> Data auto-refreshes every 5 seconds — no manual refresh needed.</div></div><span id="ovpnSvcBadge" class="badge">LIVE</span></div></div>
<div class="grid"><div class="card soft-card"><div class="muted">Total users</div><div class="kpi" id="ovpnTotalUsers"><?=count($users)?></div></div><div class="card soft-card"><div class="muted">Active connections</div><div class="kpi" id="ovpnActiveCount"><?=count($active)?></div></div><div class="card soft-card"><div class="muted">UDP Port</div><div class="kpi" id="ovpnUdpPort"><?=esc(cfgv('OVPN_UDP_PORT','1194'))?></div></div><div class="card soft-card"><div class="muted">TCP Port</div><div class="kpi" id="ovpnTcpPort"><?=esc(cfgv('OVPN_TCP_PORT','8443'))?></div></div></div>
<?php if($msg): ?><div class="flash" style="margin-top:18px"><?=esc($msg)?></div><?php endif; ?><?php if($err): ?><div class="flash error" style="margin-top:18px"><?=esc($err)?></div><?php endif; ?>
<div class="card" style="margin-top:18px"><h2 class="section-title">Add OpenVPN user</h2><form method="post"><input type="hidden" name="action" value="add"><div class="grid"><input name="username" placeholder="Username" required><input name="password" placeholder="Password" required></div><br><button class="btn green">Create OpenVPN User</button></form></div>
<div class="card" style="margin-top:18px"><h2 class="section-title">OpenVPN Users</h2><div class="table-wrap"><table style="min-width:1000px"><thead><tr><th>Username</th><th>Status</th><th>Active Devices</th><th>Edit Password</th><th>Actions</th></tr></thead><tbody id="ovpnUsersBody"><?php foreach($users as $u): $name=$u['username']; ?><tr><td><strong><?=esc($name)?></strong></td><td><?=((int)$u['blocked']===1)?'<span class="badge red">Blocked</span>':'<span class="badge green">Active</span>'?></td><td><span class="badge"><?=esc($activeBy[$name]??0)?> connected</span></td><td><form method="post" class="actions"><input type="hidden" name="action" value="edit"><input type="hidden" name="edit_username" value="<?=esc($name)?>"><input name="edit_password" placeholder="New password" required><button class="btn">Update</button></form></td><td class="actions"><a class="btn green" href="download.php?u=<?=urlencode($name)?>">Download</a><form method="post" style="display:inline"><input type="hidden" name="username" value="<?=esc($name)?>"><?php if((int)$u['blocked']===1): ?><button class="btn yellow" name="action" value="unblock">Unblock</button><?php else: ?><button class="btn red" name="action" value="block">Block</button><?php endif; ?></form><form method="post" style="display:inline" onsubmit="return confirm('Delete this user?')"><input type="hidden" name="username" value="<?=esc($name)?>"><button class="btn red" name="action" value="delete">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" style="margin-top:18px"><div class="toolbar"><h2 class="section-title">OpenVPN Active Connected Devices</h2><span class="badge green"><span id="ovpnActiveBadge"><?=count($active)?></span> active</span></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Protocol</th><th>GUI Version</th><th>Real IP</th><th>Virtual IP</th><th>Since</th><th>Download</th><th>Upload</th></tr></thead><tbody id="ovpnActiveBody"><?php if(!$active): ?><tr><td colspan="8" class="empty">No active OpenVPN devices.</td></tr><?php else: foreach($active as $c): $u=$c['username']?:$c['common_name']; ?><tr><td><strong><?=esc($u)?></strong></td><td><span class="badge"><?=esc($c['source'])?></span></td><td class="small"><?=esc($c['gui_version']?:'-')?></td><td><?=esc($c['real_address'])?></td><td><?=esc($c['virtual_address']?:'-')?></td><td><?=esc($c['connected_since'])?></td><td><?=esc(human_bytes($c['bytes_received']))?></td><td><?=esc(human_bytes($c['bytes_sent']))?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
<div class="card" style="margin-top:18px"><h2 class="section-title">Recent OpenVPN logs</h2><div class="table-wrap"><table><thead><tr><th>Time</th><th>User</th><th>IP</th><th>Virtual IP</th><th>GUI Version</th></tr></thead><tbody id="ovpnLogsBody"><?php foreach($logs as $r): ?><tr><td><?=esc($r['event_time'])?></td><td><?=esc($r['username']?:$r['common_name'])?></td><td><?=esc($r['real_ip'])?></td><td><?=esc($r['virtual_ip'])?></td><td class="small"><?=esc($r['gui_version']?:'-')?></td></tr><?php endforeach; ?></tbody></table></div></div>
<script>
async function refreshOpenVPN(){try{const r=await fetch('api_status.php?proto=openvpn&html=1&_='+Date.now(),{cache:'no-store'});const d=await r.json();if(!d.ok)return;document.getElementById('ovpnTotalUsers').textContent=d.counts.users;document.getElementById('ovpnActiveCount').textContent=d.counts.active;document.getElementById('ovpnActiveBadge').textContent=d.counts.active;document.getElementById('ovpnUdpPort').textContent=d.ports.udp;document.getElementById('ovpnTcpPort').textContent=d.ports.tcp;const b=document.getElementById('ovpnSvcBadge');b.className='badge '+(d.running?'green':'red');b.textContent=d.running?'RUNNING':'STOPPED';document.getElementById('ovpnUsersBody').innerHTML=d.html.users;document.getElementById('ovpnActiveBody').innerHTML=d.html.active;document.getElementById('ovpnLogsBody').innerHTML=d.html.logs;}catch(e){}}
refreshOpenVPN();setInterval(refreshOpenVPN,5000);
</script>
<?php render_footer(); ?>
